name: Daily Commit

on:
  schedule:
    # Runs every day at 9:35 PM IST (16:05 UTC)
    - cron: '5 16 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a change (2025ds.study.iitm.ac.in)
        run: |
          echo "Daily commit at $(date -u)" >> daily-commit.log

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push
        run: |
          git add daily-commit.log
          git commit -m "chore: daily commit [skip ci]" || echo "No changes to commit"
          git push
