name: Daily Commit

on:
  schedule:
    - cron: '17 4 * * *' # Runs daily at 04:17 UTC
  workflow_dispatch:     # Allows manual runs too

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add commit for 22f1001519@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date -u)" >> daily_log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_log.txt
          git commit -m "Daily update: $(date -u)"
          git push
